// Generated by `npm run bump` — edit that, not this. Kept as source rather
// than injected at build time so tests, the editor and any tooling see the
// same string the players do.
//
// It is the only thing that tells two clients they are running the SAME code,
// which for a lockstep sim is the difference between a match and a desync —
// and a stale service worker is a failure with no other symptom.
export const VERSION = '0.0.7'
